from electron_atom.class_electron import electron,plot
e=electron()
p=plot()
p.plot_radial_(5,1,0)
p.plot_spherical_real(e.RealSpherical(2,0))
p.plot_spherical_imaginary(e.ImaginarySpherical(2,-1))
p.plot_wf_2d(e.normalized_wf(500,1,0,0))
p.plot_wf_2d(e.normalized_wf(500,2,0,0))
p.plot_wf_3d(e.normalized_wf3D(2,1,0))
p.plot_wf_3d(e.normalized_wf3D(3,1,0))
#p.plot_sp(e.Cartesian_definition())
#p.plot_sp2(e.Cartesian_definition())
#p.plot_sp3(e.Cartesian_definition())
#p.plot_sp2d(e.Cartesian_definition())
#p.plot_sp3d(e.Cartesian_definition())
#p.plot_sp3d2(e.Cartesian_definition())