name: Deploy Svelte to GitHub pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: Hybridization 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./Hybridization/dist


  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
